spring.application.name=user-service
server.port=8081
server.host=172.20.10.4
spring.datasource.url=jdbc:mysql://localhost:3306/microservice_erm
spring.datasource.username=new_user
spring.datasource.password=Password_here2312
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

//security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
logging.level.org.springframework.security.web.access=DEBUG

