plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'com.erm'
version '1.0-SNAPSHOT'

sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.vertx:vertx-web:4.4.3'
    implementation 'io.vertx:vertx-core:4.4.3'
    implementation 'io.vertx:vertx-jdbc-client:4.4.3'
    implementation 'mysql:mysql-connector-java:8.0.33'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'org.hibernate:hibernate-core:5.6.11.Final'
    implementation 'com.zaxxer:HikariCP:4.0.3'
    implementation 'javax.persistence:javax.persistence-api:2.2'
}

application {
    mainClass = 'com.erm.service.MainVerticle'
}
shadowJar {
    archiveClassifier.set('fat')
    mergeServiceFiles()
    manifest {
        attributes 'Main-Class': 'com.erm.service.MainVerticle' // Replace with your main class
    }
}
tasks.named('jar').configure {
    enabled = false
}

